version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    restart: always
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - redis
    restart: always
    networks:
      - app-network

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    restart: always
    networks:
      - app-network
    command: ["node", "dist/src/bullMQ/queue.consumer.js"]
    environment:
      - REDIS_HOST=redis

networks:
  app-network:
    driver: bridge
