version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - redis
    restart: always
    networks:
      - app-network

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    restart: always
    networks:
      - app-network
    command: ["node", "dist/src/bullMQ/queue.consumer.js"]

networks:
  app-network:
    driver: bridge
