name: Docker compose

on:
  workflow_run:
    workflows: [Build NestJS Project]
    types:
      - completed

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
      -
        name: Run Docker Compose
        run: docker-compose up -d 
