name: Docker compose

on:
  workflow_run:
    workflows: [Build NestJS Project]
    types:
      - completed

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      -
        name: Run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
      -
        name: Run Docker Compose
        run: docker compose up -d 
