name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build NestJS project
        run: npm run build

      - name: Start backend server
        run: |
          npm run start:dev &   # ou `start:prod` selon ton script
          sleep 10              # attendre le démarrage du serveur

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman tests
        run: |
          newman run test/kindoo.postman_collection.json \
            -e test/kindoo-env.postman_environment.json \
            --reporters cli,html \
            --reporter-html-export newman-report.html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: postman-report
          path: newman-report.html
